### ISSUE TITLE
Description typo

### ISSUE THREAD

**Issue by KokaKiwi** [Raphy/pagination-bundle#1]
```
A pagination bundle making you win time when you want paginate
```
It's `save time`, not `win time` ;)

Also, maybe say `when you want to paginate` or `when you want pagination` :)

**Comment by Raphy** [comment]
Thanks for contribution !

**Comment by KokaKiwi** [comment]
You should modify the repository description too ;)

**Comment by Raphy** [comment]
Done. :)
